/**
 * Social Network Pattern Configuration
 * Defines patterns and configurations for detecting social network platforms
 */

export interface SocialNetworkPattern {
	readonly domains: readonly RegExp[]
	readonly baseUrl: string
	readonly usernamePrefix?: string
	readonly displayName: string
	readonly exampleDomain: string
	readonly urlPattern?: RegExp
	readonly allowSubdomains?: boolean
}

export const SOCIAL_NETWORKS_PATTERNS = {
	anchor: {
		domains: [/anchor\.fm$/],
		baseUrl: 'https://anchor.fm/',
		displayName: 'Anchor',
		exampleDomain: 'anchor.fm',
		allowSubdomains: false,
	},
	angellist: {
		domains: [/angel\.co$/],
		baseUrl: 'https://angel.co/',
		displayName: 'AngelList',
		exampleDomain: 'angel.co',
		allowSubdomains: false,
	},
	behance: {
		domains: [/behance\.net$/],
		baseUrl: 'https://behance.net/',
		displayName: 'Behance',
		exampleDomain: 'behance.net',
		allowSubdomains: false,
	},
	bluesky: {
		domains: [/bsky\.app$/, /bsky\.social$/],
		baseUrl: 'https://bsky.app/profile/',
		displayName: 'Bluesky',
		exampleDomain: 'bsky.app',
		allowSubdomains: false,
	},
	clubhouse: {
		domains: [/joinclubhouse\.com$/, /clubber\.one$/],
		baseUrl: 'https://joinclubhouse.com/@',
		usernamePrefix: '@',
		displayName: 'Clubhouse',
		exampleDomain: 'joinclubhouse.com',
		allowSubdomains: false,
	},
	devto: {
		domains: [/dev\.to$/],
		baseUrl: 'https://dev.to/',
		displayName: 'Dev.to',
		exampleDomain: 'dev.to',
		allowSubdomains: false,
	},
	discord: {
		domains: [
			/discord\.com$/,
			/discord\.gg$/,
			/discordapp\.com$/,
			/discord\.media$/,
			/discordapp\.net$/,
			/discordstatus\.com$/,
			/com\.discord$/,
		],
		baseUrl: 'https://discord.com/users/',
		displayName: 'Discord',
		exampleDomain: 'discord.com',
		allowSubdomains: true,
	},
	dribbble: {
		domains: [/dribbble\.com$/],
		baseUrl: 'https://dribbble.com/',
		displayName: 'Dribbble',
		exampleDomain: 'dribbble.com',
		allowSubdomains: false,
	},
	facebook: {
		domains: [
			/facebook\.com$/,
			/fbcdn\.net$/,
			/tfbnw\.net$/,
			/messenger\.com$/,
			/m\.me$/,
			/fb\.com$/,
			/fbcdn\.com$/,
			/facebook\.net$/,
			/fbsbx\.com$/,
			/fb\.me$/,
			/thefacebook\.com$/,
			/com\.facebook\.lite$/,
		],
		baseUrl: 'https://facebook.com/',
		displayName: 'Facebook',
		exampleDomain: 'facebook.com',
		allowSubdomains: true,
	},
	github: {
		domains: [/github\.com$/],
		baseUrl: 'https://github.com/',
		displayName: 'GitHub',
		exampleDomain: 'github.com',
		allowSubdomains: false,
	},
	gitlab: {
		domains: [/gitlab\.com$/],
		baseUrl: 'https://gitlab.com/',
		displayName: 'GitLab',
		exampleDomain: 'gitlab.com',
		allowSubdomains: false,
	},
	instagram: {
		domains: [
			/instagram\.com$/,
			/cdninstagram\.com$/,
			/com\.instagram\.android$/,
			/instagram\.c10r\.facebook\.com$/,
			/instagramstatic-a\.akamaihd\.net$/,
		],
		baseUrl: 'https://instagram.com/',
		displayName: 'Instagram',
		exampleDomain: 'instagram.com',
		allowSubdomains: true,
	},
	linkedin: {
		domains: [
			/linkedin\.com$/,
			/linkedin\.cn$/,
			/linkedin\.net$/,
			/linkedin\.co\.uk$/,
			/linkedin\.com\.br$/,
			/linkedin\.com\.au$/,
			/lnkd\.in$/,
			/com\.linkedin\.android$/,
		],
		baseUrl: 'https://linkedin.com/in/',
		displayName: 'LinkedIn',
		exampleDomain: 'linkedin.com',
		allowSubdomains: true,
	},
	mastodon: {
		domains: [/mastodon\.social$/, /mastodon\.world$/, /fosstodon\.org$/],
		baseUrl: 'https://mastodon.social/@',
		usernamePrefix: '@',
		displayName: 'Mastodon',
		exampleDomain: 'mastodon.social',
		allowSubdomains: false,
	},
	medium: {
		domains: [/medium\.com$/, /com\.medium\.reader$/, /com\.medium$/],
		baseUrl: 'https://medium.com/@',
		usernamePrefix: '@',
		displayName: 'Medium',
		exampleDomain: 'medium.com',
		allowSubdomains: true,
	},
	onlyfans: {
		domains: [/onlyfans\.com$/],
		baseUrl: 'https://onlyfans.com/',
		displayName: 'OnlyFans',
		exampleDomain: 'onlyfans.com',
		allowSubdomains: false,
	},
	pinterest: {
		domains: [
			/pinterest\.com$/,
			/pinterest\.co\.uk$/,
			/pinterest\.ca$/,
			/pinterest\.com\.au$/,
			/pinterest\.de$/,
			/pinterest\.fr$/,
			/pinterest\.it$/,
			/pinterest\.jp$/,
			/pin\.it$/,
			/pinimg\.com$/,
			/com\.pinterest$/,
		],
		baseUrl: 'https://pinterest.com/',
		displayName: 'Pinterest',
		exampleDomain: 'pinterest.com',
		allowSubdomains: true,
	},
	producthunt: {
		domains: [/producthunt\.com$/],
		baseUrl: 'https://producthunt.com/@',
		usernamePrefix: '@',
		displayName: 'Product Hunt',
		exampleDomain: 'producthunt.com',
		allowSubdomains: false,
	},
	qq: {
		domains: [
			/qq\.com$/,
			/myqcloud\.com$/,
			/qcloud\.com$/,
			/tencent-cloud\.com$/,
			/com\.tencent\.mobileqq$/,
		],
		baseUrl: 'https://user.qzone.qq.com/',
		displayName: 'QQ',
		exampleDomain: 'qq.com',
		allowSubdomains: true,
	},
	quora: {
		domains: [/quora\.com$/, /com\.quora\.android$/],
		baseUrl: 'https://quora.com/profile/',
		displayName: 'Quora',
		exampleDomain: 'quora.com',
		allowSubdomains: false,
	},
	reddit: {
		domains: [
			/reddit\.com$/,
			/redd\.it$/,
			/redditgifts\.com$/,
			/redditmedia\.com$/,
			/redditstatic\.com$/,
			/com\.reddit\.frontpage$/,
		],
		baseUrl: 'https://reddit.com/u/',
		displayName: 'Reddit',
		exampleDomain: 'reddit.com',
		allowSubdomains: true,
	},
	slack: {
		domains: [/slack\.com$/, /com\.slack$/, /slack-redir\.net$/],
		baseUrl: 'https://slack.com/app_redirect?team=',
		displayName: 'Slack',
		exampleDomain: 'slack.com',
		allowSubdomains: true,
	},
	snapchat: {
		domains: [/snapchat\.com$/, /com\.snapchat\.android$/],
		baseUrl: 'https://snapchat.com/add/',
		displayName: 'Snapchat',
		exampleDomain: 'snapchat.com',
		allowSubdomains: false,
	},
	spotify: {
		domains: [/spotify\.com$/],
		baseUrl: 'https://open.spotify.com/user/',
		displayName: 'Spotify',
		exampleDomain: 'spotify.com',
		allowSubdomains: false,
	},
	substack: {
		domains: [/substack\.com$/],
		baseUrl: 'https://substack.com/@',
		usernamePrefix: '@',
		displayName: 'Substack',
		exampleDomain: 'substack.com',
		allowSubdomains: false,
	},
	telegram: {
		domains: [
			/t\.me$/,
			/telegram\.me$/,
			/telegram\.org$/,
			/org\.telegram\.messenger$/,
		],
		baseUrl: 'https://t.me/',
		displayName: 'Telegram',
		exampleDomain: 't.me',
		allowSubdomains: false,
	},
	threads: {
		domains: [/threads\.net$/],
		baseUrl: 'https://threads.net/@',
		usernamePrefix: '@',
		displayName: 'Threads',
		exampleDomain: 'threads.net',
		allowSubdomains: false,
	},
	tiktok: {
		domains: [
			/tiktok\.com$/,
			/tiktokv\.com$/,
			/tiktokcdn\.com$/,
			/musical\.ly$/,
			/douyin\.com$/,
			/com\.zhiliaoapp\.musically$/,
		],
		baseUrl: 'https://tiktok.com/@',
		usernamePrefix: '@',
		displayName: 'TikTok',
		exampleDomain: 'tiktok.com',
		allowSubdomains: true,
	},
	tumblr: {
		domains: [
			/tumblr\.com$/,
			/t\.umblr\.com$/,
			/tmblr\.co$/,
			/tumblr\.net$/,
			/com\.tumblr$/,
		],
		baseUrl: 'https://tumblr.com/blog/',
		displayName: 'Tumblr',
		exampleDomain: 'tumblr.com',
		allowSubdomains: true,
	},
	twitter: {
		domains: [
			/twitter\.com$/,
			/x\.com$/,
			/twimg\.com$/,
			/tweetdeck\.com$/,
			/t\.co$/,
			/com\.twitter\.android$/,
		],
		baseUrl: 'https://x.com/',
		displayName: 'X (Twitter)',
		exampleDomain: 'x.com',
		allowSubdomains: true,
	},
	twitch: {
		domains: [
			/twitch\.tv$/,
			/jtvnw\.net$/,
			/ttvnw\.net$/,
			/tv\.twitch\.android\.app$/,
		],
		baseUrl: 'https://twitch.tv/',
		displayName: 'Twitch',
		exampleDomain: 'twitch.tv',
		allowSubdomains: true,
	},
	vkontakte: {
		domains: [
			/vk\.com$/,
			/vkontakte\.com$/,
			/vk-cdn\.me$/,
			/vk-cdn\.net$/,
			/com\.vkontakte\.android$/,
		],
		baseUrl: 'https://vk.com/',
		displayName: 'VKontakte',
		exampleDomain: 'vk.com',
		allowSubdomains: true,
	},
	wechat: {
		domains: [
			/wechat\.org$/,
			/w\.url\.cn$/,
			/wechat\.com$/,
			/com\.tencent\.mm$/,
		],
		baseUrl: 'https://weixin.qq.com/',
		displayName: 'WeChat',
		exampleDomain: 'wechat.com',
		allowSubdomains: true,
	},
	weibo: {
		domains: [
			/weibo\.com$/,
			/weibo\.cn$/,
			/com\.weico\.international$/,
			/com\.sina\.weibo$/,
		],
		baseUrl: 'https://weibo.com/u/',
		displayName: 'Weibo',
		exampleDomain: 'weibo.com',
		allowSubdomains: true,
	},
	wikipedia: {
		domains: [/wikipedia\.org$/],
		baseUrl: 'https://en.wikipedia.org/wiki/User:',
		displayName: 'Wikipedia',
		exampleDomain: 'wikipedia.org',
		allowSubdomains: true,
	},
	whatsapp: {
		domains: [
			/whatsapp\.net$/,
			/whatsapp\.com$/,
			/whatsapp\.biz$/,
			/wa\.me$/,
			/com\.whatsapp$/,
		],
		baseUrl: 'https://wa.me/',
		displayName: 'WhatsApp',
		exampleDomain: 'wa.me',
		allowSubdomains: true,
	},
	youtube: {
		domains: [
			/youtube\.com$/,
			/youtu\.be$/,
			/youtube-nocookie\.com$/,
			/googlevideo\.com$/,
			/ytimg\.com$/,
			/com\.google\.android\.youtube$/,
		],
		baseUrl: 'https://youtube.com/@',
		usernamePrefix: '@',
		displayName: 'YouTube',
		exampleDomain: 'youtube.com',
		allowSubdomains: true,
	},
} as const satisfies Record<string, SocialNetworkPattern>

export type SocialNetworkKey = keyof typeof SOCIAL_NETWORKS_PATTERNS

// Legacy export for backward compatibility
export const socialNetworksPatterns = SOCIAL_NETWORKS_PATTERNS
